import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';

// Generated by `flutterfire configure`. Unresolved until you run it.
import 'package:futsal_booking/firebase_options.dart';

import 'messaging/messaging_service.dart';

/// Initializes Firebase, App Check and the background push handler. Call once from `main()` after
/// `WidgetsFlutterBinding.ensureInitialized()` and before `runApp`.
abstract final class FirebaseBootstrap {
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await _activateAppCheck();
    if (!kIsWeb) {
      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
    }
  }

  /// Debug builds use debug providers (register the debug token printed in
  /// the device log under Firebase console → App Check → Manage debug
  /// tokens). Release builds use Play Integrity (Android) and App Attest
  /// with DeviceCheck fallback (iOS).
  static Future<void> _activateAppCheck() {
    return FirebaseAppCheck.instance.activate(
      providerAndroid: kDebugMode
          ? const AndroidDebugProvider()
          : const AndroidPlayIntegrityProvider(),
      providerApple: kDebugMode
          ? const AppleDebugProvider()
          : const AppleAppAttestWithDeviceCheckFallbackProvider(),
    );
  }
}
