import 'package:flutter/material.dart';

/// Exact color schemes from design_system.md §2.1–2.2.
///
/// Built with the explicit [ColorScheme] constructor (not `fromSeed`) so every
/// value is exact. Unlisted optional roles fall back to Flutter defaults.
abstract final class AppColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1F4FD1),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFDCE4FF),
    onPrimaryContainer: Color(0xFF0A2472),
    secondary: Color(0xFF4F5B76),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDDE3F3),
    onSecondaryContainer: Color(0xFF111C33),
    tertiary: Color(0xFF4F5B76),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDDE3F3),
    onTertiaryContainer: Color(0xFF111C33),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFF8F9FC),
    onSurface: Color(0xFF151A23),
    surfaceDim: Color(0xFFD8DCE4),
    surfaceBright: Color(0xFFF8F9FC),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF2F4F8),
    surfaceContainer: Color(0xFFECEFF4),
    surfaceContainerHigh: Color(0xFFE6E9F0),
    surfaceContainerHighest: Color(0xFFE0E4EC),
    onSurfaceVariant: Color(0xFF4A5263),
    outline: Color(0xFF767E8F),
    outlineVariant: Color(0xFFC6CBD5),
    inverseSurface: Color(0xFF2B303A),
    onInverseSurface: Color(0xFFEFF1F6),
    inversePrimary: Color(0xFFB4C5FF),
    surfaceTint: Color(0xFF1F4FD1),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFB4C5FF),
    onPrimary: Color(0xFF002A78),
    primaryContainer: Color(0xFF1A3FA8),
    onPrimaryContainer: Color(0xFFDCE4FF),
    secondary: Color(0xFFBDC6DE),
    onSecondary: Color(0xFF273047),
    secondaryContainer: Color(0xFF3D4760),
    onSecondaryContainer: Color(0xFFDDE3F3),
    tertiary: Color(0xFFBDC6DE),
    onTertiary: Color(0xFF273047),
    tertiaryContainer: Color(0xFF3D4760),
    onTertiaryContainer: Color(0xFFDDE3F3),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0F1218),
    onSurface: Color(0xFFE2E5EC),
    surfaceDim: Color(0xFF0F1218),
    surfaceBright: Color(0xFF353A44),
    surfaceContainerLowest: Color(0xFF0A0D12),
    surfaceContainerLow: Color(0xFF171B22),
    surfaceContainer: Color(0xFF1B1F27),
    surfaceContainerHigh: Color(0xFF252A33),
    surfaceContainerHighest: Color(0xFF30353E),
    onSurfaceVariant: Color(0xFFC3C8D3),
    outline: Color(0xFF8D93A0),
    outlineVariant: Color(0xFF434956),
    inverseSurface: Color(0xFFE2E5EC),
    onInverseSurface: Color(0xFF2B303A),
    inversePrimary: Color(0xFF1F4FD1),
    surfaceTint: Color(0xFFB4C5FF),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );
}
